name: main

on:
  push:
    branches: ["v1"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm i

      - run: npm exec prettier -- --check .
        name: fmt

      - run: npm run lint
        name: lint

  test:
    needs: check

    strategy:
      fail-fast: false

      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./
        name: Run aslilac/setup@v1
        with:
          archives: |
            https://github.com/aslilac/betty/releases/download/v0.1.1/betty-v0.1.1-x86_64-unknown-linux-gnu.tar.gz
            https://github.com/aslilac/tomlq/releases/download/v0.1.0/tomlq-v0.1.0-x86_64-unknown-linux-gnu.tar.gz

      - run: betty
        working-directory: ./tests/testdata/betty/

      - run: tomlq version -f gleam.toml
        working-directory: ./tests/testdata/tomlq/
